name: Release Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  publish:
    if: (github.event_name == 'pull_request' && github.event.pull_request.merged == true) || github.event_name == 'push'
    runs-on: ubuntu-latest
    environment: release
    # this permission is required for PyPI Trusted Publisher setup
    # https://docs.pypi.org/trusted-publishers/using-a-publisher/
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build and wheel
        run: python3 -m pip install build wheel

      - name: Build package
        run: make build

      # the package name must match between setup.py and pypi
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1