name: Graphex Workflow

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  publish:
    if: (github.event_name == 'push' && startsWith(github.ref, 'refs/tags')) || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build and wheel
        run: python3 -m pip install build wheel

      - name: Build package
        run: make build

      # the package name must match between setup.py and pypi
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
